# Generated by Django 4.2.9 on 2026-03-23 04:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre comercial')),
                ('presentacion', models.CharField(max_length=100, verbose_name='Presentación')),
                ('concentracion', models.CharField(max_length=100, verbose_name='Concentración')),
                ('requiere_receta', models.BooleanField(default=False, verbose_name='¿Requiere receta?')),
                ('estado_colorimetria', models.CharField(choices=[('verde', 'Vigente'), ('amarillo', 'Próximo a caducar'), ('rojo', 'Caducado')], default='verde', max_length=10, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token')),
                ('url_qr', models.URLField(blank=True, max_length=500, verbose_name='URL de consulta')),
                ('imagen_qr', models.ImageField(blank=True, upload_to='qr/', verbose_name='Imagen QR')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('fecha_regeneracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de regeneración')),
                ('contador_escaneos', models.PositiveIntegerField(default=0, verbose_name='Escaneos')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('medicamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_qr', to='medicamentos.medicamento')),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100, verbose_name='Número de lote')),
                ('fecha_fabricacion', models.DateField(verbose_name='Fecha de fabricación')),
                ('fecha_caducidad', models.DateField(verbose_name='Fecha de caducidad')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Stock actual')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='medicamentos.medicamento')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['fecha_caducidad'],
                'unique_together': {('medicamento', 'numero_lote')},
            },
        ),
    ]
