# Generated by Django 5.0.2 on 2026-04-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('ap_pat', models.CharField(blank=True, max_length=60, null=True)),
                ('ap_mat', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
