# Generated by Django 5.0.2 on 2026-04-15 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(max_length=60)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('stock_actual', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_prov', models.ForeignKey(db_column='id_prov', on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'db_table': 'lote',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_med', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('presentacion', models.CharField(blank=True, max_length=80, null=True)),
                ('concentracion', models.CharField(blank=True, max_length=60, null=True)),
                ('requiere_receta', models.BooleanField(default=False)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('estado_colorimetria', models.CharField(choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo'), ('sin_stock', 'Sin Stock')], default='sin_stock', max_length=20)),
                ('id_lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.CASCADE, to='medicamentos.lote')),
            ],
            options={
                'db_table': 'medicamento',
            },
        ),
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id_qr', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('url_qr', models.CharField(max_length=255)),
                ('fecha_generacion', models.DateField(blank=True, null=True)),
                ('fecha_regeneracion', models.DateField(blank=True, null=True)),
                ('contador_escaneos', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('id_medicamento', models.ForeignKey(db_column='id_medicamento', on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento')),
            ],
            options={
                'db_table': 'codigos_qr',
            },
        ),
    ]
