# Generated by Django 5.0.2 on 2026-04-20 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_lote_oculto_por_caducidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
