# Generated by Django 5.0.2 on 2026-04-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=60, unique=True)),
                ('rol', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=80)),
                ('ap_pat', models.CharField(blank=True, max_length=60, null=True)),
                ('ap_mat', models.CharField(blank=True, max_length=60, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
