# Generated by Django 5.0.2 on 2026-04-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Ultimo dia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de contratacion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puesto',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Puesto'),
        ),
    ]
